# -*- coding: utf-8 -*-
"""
/***************************************************************************
 s2layer_factory
                                 A QGIS plugin
 Create Sentinel-2 layers using Google Earth Engine
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-25
        copyright            : (C) 2021 by Earth Observation Lab / CNES
        email                : eolab.cnes@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load s2layer_factory class from file s2layer_factory.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_sentinel2_geelayers import s2layer_factory
    return s2layer_factory(iface)
